From conda/miniconda3:latest

LABEL Python score box - base

USER root

RUN pip install --upgrade pip; \
    pip install dill numpy jsonify pandas scipy sklearn statsmodels; \
    pip install flask gunicorn;

WORKDIR /pybox/app

COPY app    /pybox/app
COPY model  /pybox/model

EXPOSE 8080:8080
ENTRYPOINT ["/bin/bash", "startServer.sh"]

